/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/

var __defProp = Object.defineProperty;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __getOwnPropNames = Object.getOwnPropertyNames;
var __hasOwnProp = Object.prototype.hasOwnProperty;
var __export = (target, all) => {
  for (var name in all)
    __defProp(target, name, { get: all[name], enumerable: true });
};
var __copyProps = (to, from, except, desc) => {
  if (from && typeof from === "object" || typeof from === "function") {
    for (let key of __getOwnPropNames(from))
      if (!__hasOwnProp.call(to, key) && key !== except)
        __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });
  }
  return to;
};
var __toCommonJS = (mod) => __copyProps(__defProp({}, "__esModule", { value: true }), mod);

// src/main.ts
var main_exports = {};
__export(main_exports, {
  default: () => InsiderPlugin
});
module.exports = __toCommonJS(main_exports);
var import_obsidian9 = require("obsidian");

// src/settings.ts
var import_obsidian = require("obsidian");

// src/types.ts
var DEFAULT_TOGGLES = {
  recommend_note_ideas: true,
  compare_existing_notes: true,
  estimate_token_usage: true,
  include_timestamps: true,
  strip_audio_cues: true
};
var DEFAULT_SETTINGS = {
  deepseek_api_key: "",
  twitter_bearer_token: "",
  output_folder: "To-Process",
  model: "deepseek-chat",
  api_base_url: "https://api.deepseek.com",
  mode: "report",
  custom_style_prompt: "",
  related_notes_mode: "snapshot",
  toggles: { ...DEFAULT_TOGGLES },
  max_related_notes: 5,
  reddit_max_comments: 30
};

// src/settings.ts
var InsiderSettingTab = class extends import_obsidian.PluginSettingTab {
  constructor(app, plugin) {
    super(app, plugin);
    this.plugin = plugin;
  }
  display() {
    const { containerEl } = this;
    containerEl.empty();
    new import_obsidian.Setting(containerEl).setName("Insider settings").setHeading();
    new import_obsidian.Setting(containerEl).setName("DeepSeek API key").setDesc("Stored locally in your vault's plugin data.").addText(
      (text) => text.setPlaceholder("sk-...").setValue(this.plugin.settings.deepseek_api_key).onChange(async (value) => {
        this.plugin.settings.deepseek_api_key = value;
        await this.plugin.saveSettings();
      })
    );
    new import_obsidian.Setting(containerEl).setName("Output folder").setDesc("Folder inside your vault where new notes are written.").addText(
      (text) => text.setPlaceholder("To-Process").setValue(this.plugin.settings.output_folder).onChange(async (value) => {
        this.plugin.settings.output_folder = value || "To-Process";
        await this.plugin.saveSettings();
      })
    );
    new import_obsidian.Setting(containerEl).setName("Model").addText(
      (text) => text.setValue(this.plugin.settings.model).onChange(async (value) => {
        this.plugin.settings.model = value || DEFAULT_SETTINGS.model;
        await this.plugin.saveSettings();
      })
    );
    new import_obsidian.Setting(containerEl).setName("API base URL").addText(
      (text) => text.setValue(this.plugin.settings.api_base_url).onChange(async (value) => {
        this.plugin.settings.api_base_url = value || DEFAULT_SETTINGS.api_base_url;
        await this.plugin.saveSettings();
      })
    );
    new import_obsidian.Setting(containerEl).setName("X/Twitter bearer token").setDesc("Optional \u2014 required for X/Twitter sources.").addText(
      (text) => text.setValue(this.plugin.settings.twitter_bearer_token).onChange(async (value) => {
        this.plugin.settings.twitter_bearer_token = value;
        await this.plugin.saveSettings();
      })
    );
    new import_obsidian.Setting(containerEl).setName("Custom style prompt").setDesc("Optional extra instructions appended to every generation.").addTextArea((area) => {
      area.setValue(this.plugin.settings.custom_style_prompt).onChange(async (value) => {
        this.plugin.settings.custom_style_prompt = value;
        await this.plugin.saveSettings();
      });
      area.inputEl.rows = 3;
    });
  }
};
function mergeSettings(raw) {
  var _a;
  const base = structuredClone(DEFAULT_SETTINGS);
  if (!raw) return base;
  return {
    ...base,
    ...raw,
    toggles: { ...base.toggles, ...(_a = raw.toggles) != null ? _a : {} },
    mode: raw.mode === "summary" ? "summary" : "report",
    related_notes_mode: raw.related_notes_mode === "keyword" ? "keyword" : "snapshot"
  };
}

// src/views/InsiderView.ts
var import_obsidian8 = require("obsidian");

// src/ai/deepseek.ts
var import_obsidian2 = require("obsidian");

// src/prompts.ts
var NOTE_TITLE_RULES = `Filename title requirements (NOTE_TITLE line):
- Clear, specific, and searchable
- Capture the central idea, not just the broad topic
- Avoid clickbait, vague phrases, and decorative wording
- Avoid colon subtitles by default. Use a colon only if the second half adds necessary specificity rather than restating the first half.
- Do not use academic filler like "A Research Note on," "An Analysis of," or "A Reflection on."
- Do not include the note generation date`;
var MARKDOWN_STYLE_RULES = `Markdown styling rules for the main note body:
- Use clean, readable Markdown.
- Use level 1 headings (\`#\`) for major sections, including sections like \`# Related Notes\` and \`# Future Note Ideas\` if they are included.
- Always leave one blank line after every heading before the section content begins.
- Use a wider range of heading levels (\`##\`, \`###\`, and occasionally deeper levels) when they help organize the note's hierarchy.
- Headings should clarify the structure of the note, not decorate it.
- Use **bold** for key terms, central claims, and important distinctions.
- Use *italics* sparingly for emphasis, especially for nuanced qualifications or conceptual contrasts.
- Use bullet points for lists of ideas, takeaways, examples, implications, or evidence.
- Use numbered lists when sequence, priority, or step-by-step logic matters.
- Use tables when comparing concepts, arguments, tradeoffs, methods, or evidence.
- Start new paragraphs when the focus shifts, when a point needs room to breathe, or when readability improves.
- Paragraph length should follow the complexity of the idea: some paragraphs may be short, while others may be longer when developing a connected argument.
- Avoid unnecessary decorative formatting. Formatting should clarify the note.
- Keep Obsidian compatibility in mind: use standard Markdown and \`[[Note Title]]\` links.
- Do not start the body with a level-1 heading that repeats the NOTE_TITLE.`;
var DIRECT_QUESTION_USER_PROMPT = `Answer the user's question as a nuanced research-style report.

First, determine the best response mode:
- Reasoning mode: use when the question is conceptual, philosophical, strategic, reflective, or can be answered mainly through logic and careful argument.
- Research mode: use when the question depends on current facts, recent developments, statistics, laws, prices, product/tool comparisons, scientific findings, named external sources, or factual claims that should be verified.
- Hybrid mode: use when the question requires both conceptual reasoning and factual support.

If research mode or hybrid mode is needed, use the provided source material and retrieved sources. Do not pretend to have researched sources that were not provided.

Report requirements:
1. State the question being answered in precise terms.
2. Give a direct answer or thesis early.
3. Break the issue into the most important dimensions.
4. Present competing interpretations or counterarguments.
5. Stress-test the main answer by asking what would make it wrong, incomplete, or misleading.
6. Separate evidence-based claims from reasoning-based claims.
7. Use related notes only when they genuinely deepen, challenge, support, or contextualize the answer.
8. Avoid generic nuance. Every qualification should change how the reader thinks or acts.
9. Do not overclaim. Mark uncertainty clearly.
10. End with a practical takeaway, decision framework, or refined conclusion.

Style:
- Clear, structured, and intellectually honest.
- Prefer precise claims over broad statements.
- Avoid filler phrases.
- Do not ask the user questions unless the task cannot be answered without missing information.`;
var REPORT_MODE_PROMPT = `Write a source-grounded research note based on the provided source material.

Primary goal:
Accurately explain what the source says, how it argues, what evidence it uses, and what should or should not be concluded from it.

Use the source as the primary authority. Do not add outside facts unless they are explicitly included in the input.

Use the following structure as a guide, not a rigid checklist. Include the sections that are relevant to the source. If a section has little useful content, merge it into another section or omit it rather than forcing filler.

Suggested structure:
1. Central thesis:
State the source's main claim, purpose, or conclusion.

2. Context:
Explain the problem, question, debate, or situation the source is responding to.

3. Argument map:
Break down the source's reasoning into its major steps, sections, or moves.

4. Evidence:
Identify the key evidence used: studies, examples, anecdotes, data, cases, demonstrations, formulas, quotations, observations, or personal experiences.

5. Source evaluation:
Evaluate the strength of the source's reasoning based only on the provided material. Note whether the evidence strongly supports the conclusion, only partially supports it, or leaves important gaps.

6. Limitations and uncertainty:
Explain what the source does not prove, where the source is ambiguous, where the material may be incomplete, and what should not be overclaimed.

7. Implications:
Explain the practical, intellectual, or personal takeaways that reasonably follow from the source.

Rules:
- Be faithful to the provided material.
- Clearly separate the source's claims from your own interpretation.
- Do not invent claims, names, citations, studies, statistics, examples, timestamps, formulas, events, or conclusions.
- If the source material is ambiguous, incomplete, auto-transcribed, OCR-derived, or missing context, mark uncertainty briefly and avoid overclaiming.
- Preserve important distinctions, mechanisms, metaphors, examples, tensions, and qualifications.
- Prefer precise claims over generic summaries.
- Do not create related-note links or compare this source to existing vault notes; that will be handled separately.`;
var SUMMARY_MODE_PROMPT = `Write a concise source-grounded summary based on the provided source material.

Primary goal:
Accurately explain the source's main point, important supporting details, and reasonable takeaways without adding unsupported outside information.

Use the following structure as a guide, not a rigid checklist. Include only the parts that are useful for this source. If a part has little relevant content, merge it into another part or omit it rather than forcing filler.

Suggested structure:
1. Main point:
State the source's central claim, purpose, or conclusion.

2. Key takeaways:
List the most important ideas from the source.

3. Evidence or examples:
Identify important evidence, examples, anecdotes, mechanisms, formulas, data, or observations used in the source.

4. Reasonable implications:
Explain what someone can reasonably learn or apply from the source.

5. Do not overclaim:
Briefly state what the source does not prove or where the material is uncertain.

Rules:
- Be faithful to the source.
- Do not add outside facts unless they are explicitly included in the input.
- Clearly separate the source's claims from your own interpretation.
- Do not invent claims, names, citations, studies, statistics, examples, timestamps, formulas, events, or conclusions.
- If the material is ambiguous, incomplete, auto-transcribed, OCR-derived, or missing context, mark uncertainty briefly and avoid overclaiming.
- Prefer precise claims over generic summaries.
- Do not create related-note links or compare this source to existing vault notes; that will be handled separately.`;
function noteOutputInstructions(opts) {
  var _a, _b, _c, _d;
  const created = (_a = opts.date_created) != null ? _a : (/* @__PURE__ */ new Date()).toISOString().slice(0, 10);
  const lines = [
    "## Note output format (follow exactly)",
    "",
    "Return only the finished note file content in this order:",
    "1. First line: `NOTE_TITLE: <filename title>`",
    "2. YAML frontmatter block",
    "3. Main note body",
    "",
    "The NOTE_TITLE becomes the Markdown filename. Do not put the note title in frontmatter and do not use it as the body's opening level-1 heading.",
    "",
    NOTE_TITLE_RULES,
    "",
    "### YAML frontmatter",
    `- Include \`date_created: ${created}\``,
    "- Do not include a `title` property"
  ];
  if (opts.source_generation) {
    lines.push(
      `- Include \`source_url: "${(_b = opts.source_url) != null ? _b : ""}"\` exactly as provided`,
      `- Include \`content_type: ${(_c = opts.content_type) != null ? _c : ""}`,
      "- Do not include `source` or `source: insider`"
    );
  } else {
    lines.push(
      "- Include `question:` with the user's question verbatim",
      "- Use a YAML block scalar (`|`) if the question spans multiple lines",
      "",
      "User question (copy verbatim into frontmatter):",
      ((_d = opts.question) == null ? void 0 : _d.trim()) || "(see source text below)"
    );
  }
  lines.push("", MARKDOWN_STYLE_RULES);
  return lines.join("\n");
}
function baseSystemPrompt(settings, sourceGeneration = true) {
  if (!sourceGeneration) {
    return "You write excellent Obsidian markdown notes.\n";
  }
  return (settings.mode === "report" ? REPORT_MODE_PROMPT : SUMMARY_MODE_PROMPT) + "\n";
}
function buildUserPrompt(opts) {
  var _a, _b, _c;
  const parts = [];
  const sourceGeneration = (_a = opts.source_generation) != null ? _a : true;
  const includeOutput = (_b = opts.include_output_instructions) != null ? _b : true;
  if (includeOutput) {
    parts.push(
      noteOutputInstructions({
        source_generation: sourceGeneration,
        source_url: opts.source_url,
        content_type: opts.content_type,
        question: opts.question
      }),
      ""
    );
  }
  parts.push(`# Source: ${opts.source_label}`, "", opts.source_text.trim());
  if (opts.user_prompt.trim()) {
    if (sourceGeneration) {
      parts.push(
        "",
        "## User optional instructions",
        "Apply these optional instructions. If they conflict with the source-generation guidelines, these user optional instructions override those guidelines.",
        opts.user_prompt.trim()
      );
    } else {
      parts.push("", "## User instructions", opts.user_prompt.trim());
    }
  }
  if (opts.settings.toggles.compare_existing_notes && opts.related_notes.length) {
    parts.push("", "## Related notes in vault (for compare/contrast)");
    for (const note of opts.related_notes) {
      parts.push(`### [[${note.title}]] (${note.relative_path})`);
      parts.push(note.body.slice(0, 2500));
      parts.push("");
    }
  }
  if (opts.settings.toggles.compare_existing_notes && ((_c = opts.related_links) == null ? void 0 : _c.trim())) {
    parts.push(
      "",
      "## Validated related note links",
      "Include these validated links in a `# Related Notes` section in the finished note body.",
      opts.related_links.trim()
    );
  }
  if (opts.snapshotContext) {
    parts.push("", opts.snapshotContext);
  }
  if (opts.settings.toggles.recommend_note_ideas) {
    parts.push(
      "",
      "## Required closing section",
      "End the note with a section titled `# Future Note Ideas` containing 3-5 ",
      "specific [[wiki-style]] note titles the user could create next, each with one sentence explaining why."
    );
  }
  return parts.join("\n");
}

// src/tokens.ts
var CHARS_PER_TOKEN = 4;
var MESSAGE_OVERHEAD_TOKENS = 8;
function estimateTokens(text) {
  return text ? Math.max(1, Math.round(text.length / CHARS_PER_TOKEN)) : 0;
}
function estimateMessagesTokens(system, user) {
  return estimateTokens(system) + estimateTokens(user) + MESSAGE_OVERHEAD_TOKENS * 2;
}
function combineEstimates(label, estimates) {
  return {
    label,
    input_tokens: estimates.reduce((s, e) => s + e.input_tokens, 0),
    output_tokens: estimates.reduce((s, e) => s + e.output_tokens, 0),
    calls: estimates.reduce((s, e) => s + e.calls, 0)
  };
}
function totalTokens(e) {
  return e.input_tokens + e.output_tokens;
}
function formatTokenEstimate(e) {
  const calls = e.calls ? `, ${e.calls} call${e.calls !== 1 ? "s" : ""}` : "";
  return `${e.label}: ~${e.input_tokens.toLocaleString()} input, ~${e.output_tokens.toLocaleString()} output${calls}`;
}

// src/ai/deepseek.ts
var CHUNK_CHARS = 28e3;
var MERGE_THRESHOLD = 32e3;
var EXPECTED_NOTE_OUTPUT_TOKENS = 2e3;
var EXPECTED_SUMMARY_OUTPUT_TOKENS = 900;
var EXPECTED_PARTIAL_OUTPUT_TOKENS = 1400;
var EXPECTED_SNAPSHOT_OUTPUT_TOKENS = 260;
var EXPECTED_RELATED_LINK_OUTPUT_TOKENS = 900;
var SNAPSHOT_PROMPT_TEMPLATE = `You are creating a compact semantic snapshot of an Obsidian note for future AI retrieval.

Purpose:
The snapshot will help a future AI system discover related notes, suggest backlinks, compare ideas, and generate new notes. It is not user-facing feedback.

Input:
- Note title: {note_title}
- Relative path: {relative_file_path}
- Note content: {note_content}

Output exactly this format:

## [[{note_title}]]
Path: {relative_file_path}
Core: <one sentence capturing the note's main claim, purpose, situation, factual focus, or way of thinking>
Evidence: <semicolon-separated sources, examples, anecdotes, papers, books, people, personal experiences, formulas, datasets, or "none">
Tethers: <3\u20136 semicolon-separated trigger phrases for when this note should be resurfaced>

Rules:
- Do not ask the user questions.
- Do not give feedback about the note.
- Do not comment on note quality or clarity.
- Do not invent sources, claims, people, books, studies, formulas, or events.
- Preserve distinctive examples, mechanisms, metaphors, formulas, emotional patterns, factual distinctions, and tensions.
- Keep the snapshot compact and useful for future connection discovery.
- The Path field must exactly match the provided relative path.`;
var RELATED_LINK_PROMPT_TEMPLATE = `You are an Obsidian vault connection engine.

Purpose:

Use the provided related-note context to find existing notes that would meaningfully enrich the new note. Do not rely only on keyword overlap.

Inputs:

- New note title: {new_note_title}

- New note draft or source material: {new_note_content}

- Related-note mode: {related_note_mode}

- Related-note context: {related_note_context}

Connection lenses:

Use four broad lenses:

1. Idea:

The existing note shares, extends, deepens, or relates to the new note's main idea, focus, question, mechanism, or way of thinking.

2. Evidence:

The existing note uses the same or related source, personal story, anecdote, research paper, book, person, formula, dataset, example, or quoted idea.

3. Application:

One note applies, illustrates, operationalizes, or gives a concrete case of the other.

4. Tension:

The existing note challenges, contrasts with, complicates, or adds a useful limitation to the new note.

Context usage:

- Snapshot mode uses the provided vault snapshot. Snapshot fields such as Core, Evidence, and Tethers show what each note is mainly about, what sources/examples it uses, and when it may be relevant.

- Keyword mode uses only the keyword-selected candidate notes. These notes have already been selected by the keyword search algorithm; your job is to apply the Idea/Evidence/Application/Tension framework to those candidates and explain the strongest useful connections.

Usefulness test:

Only include a related note if linking it would help a future reader understand, apply, question, or deepen the new note.

Selection rules:

- Prefer 3\u20137 strong related notes.

- Prefer semantic connections over simple keyword overlap.

- Avoid generic connections like "both are about learning" unless the reason is specific.

- Use only notes present in the related-note context.

- Use only note titles in double brackets for direct access instead of folder paths.

- Do not mention missing, deleted, moved, or omitted notes.

- Do not invent notes, titles, sources, or claims.

- Do not ask the user questions.

- Do not give feedback about the vault or note quality.

Output:

Return only validated related notes in this compact format:

Related notes:

- [[Note Title]] | Lens: Idea/Evidence/Application/Tension | Reason: 3-5 sentences.`;
function optionalInstructionsBlock(userPrompt) {
  const prompt = userPrompt.trim();
  if (!prompt) return "";
  return "\n\n## User optional instructions\nApply these optional instructions. If they conflict with the source-generation guidelines, these user optional instructions override those guidelines.\n" + prompt;
}
function getApiKey(settings) {
  const key = settings.deepseek_api_key.trim();
  if (!key) throw new Error("DeepSeek API key missing. Add it in Insider settings.");
  return key;
}
async function complete(settings, system, user) {
  var _a, _b, _c, _d;
  const url = `${settings.api_base_url.replace(/\/$/, "")}/v1/chat/completions`;
  const resp = await (0, import_obsidian2.requestUrl)({
    url,
    method: "POST",
    headers: {
      "Content-Type": "application/json",
      Authorization: `Bearer ${getApiKey(settings)}`
    },
    body: JSON.stringify({
      model: settings.model,
      messages: [
        { role: "system", content: system },
        { role: "user", content: user }
      ],
      temperature: 0.4
    })
  });
  if (resp.status >= 400) {
    throw new Error(`DeepSeek API error (${resp.status}): ${resp.text}`);
  }
  const data = resp.json;
  const text = ((_d = (_c = (_b = (_a = data.choices) == null ? void 0 : _a[0]) == null ? void 0 : _b.message) == null ? void 0 : _c.content) != null ? _d : "").trim();
  if (!text) throw new Error("Model returned an empty response.");
  return text;
}
function chunkText(text, size = CHUNK_CHARS) {
  if (text.length <= size) return [text];
  const chunks = [];
  let start = 0;
  while (start < text.length) {
    let end = Math.min(start + size, text.length);
    if (end < text.length) {
      const breakAt = text.lastIndexOf("\n", end);
      if (breakAt > start + size / 2) end = breakAt;
    }
    chunks.push(text.slice(start, end));
    start = end;
  }
  return chunks;
}
async function generateNote(opts) {
  var _a, _b, _c, _d, _e, _f, _g, _h, _i;
  const warnings = [];
  const settings = opts.settings;
  const related = (_a = opts.related_notes) != null ? _a : [];
  const sourceGeneration = (_b = opts.source_generation) != null ? _b : true;
  const system = baseSystemPrompt(settings, sourceGeneration);
  const promptOpts = {
    settings,
    source_label: opts.source_label,
    source_text: opts.source_text,
    user_prompt: (_c = opts.user_prompt) != null ? _c : "",
    related_notes: related,
    related_links: (_d = opts.related_links) != null ? _d : "",
    source_generation: sourceGeneration,
    source_url: (_e = opts.source_url) != null ? _e : "",
    content_type: (_f = opts.content_type) != null ? _f : "",
    question: (_g = opts.question) != null ? _g : "",
    snapshotContext: opts.snapshotContext
  };
  if (opts.source_text.length <= MERGE_THRESHOLD) {
    const user = buildUserPrompt(promptOpts);
    return { body: await complete(settings, system, user), warnings };
  }
  const chunks = chunkText(opts.source_text);
  warnings.push(`Long source (${opts.source_text.length.toLocaleString()} chars) \u2014 processing in ${chunks.length} parts.`);
  const partials = [];
  for (let i = 0; i < chunks.length; i++) {
    const partialPrompt = `This is part ${i + 1}/${chunks.length} of a long source (${opts.source_label}). Produce a detailed partial analysis only. Do not include NOTE_TITLE, YAML frontmatter, or final note formatting.

# Source: ${opts.source_label}

${chunks[i]}` + optionalInstructionsBlock((_h = opts.user_prompt) != null ? _h : "");
    partials.push(await complete(settings, system, partialPrompt));
  }
  let mergePrompt = noteOutputInstructions({
    source_generation: sourceGeneration,
    source_url: opts.source_url,
    content_type: opts.content_type,
    question: opts.question
  }) + `

Merge these ${partials.length} partial analyses of '${opts.source_label}' into one cohesive finished note file using the output format above.

` + partials.join("\n\n---\n\n") + optionalInstructionsBlock((_i = opts.user_prompt) != null ? _i : "");
  if (settings.toggles.compare_existing_notes && related.length) {
    mergePrompt += "\n\n" + buildUserPrompt({ ...promptOpts, source_text: "(see partials above)", user_prompt: "", include_output_instructions: false });
  }
  return { body: await complete(settings, system, mergePrompt), warnings };
}
function buildSnapshotPrompt(note_title, relative_file_path, note_content) {
  return SNAPSHOT_PROMPT_TEMPLATE.replace(/\{note_title\}/g, note_title).replace(/\{relative_file_path\}/g, relative_file_path).replace(/\{note_content\}/g, note_content);
}
async function summarizeForSnapshot(settings, title, relative_path, body) {
  const prompt = buildSnapshotPrompt(title, relative_path, body);
  return complete(settings, "Follow the user's instructions exactly.", prompt);
}
function buildRelatedLinkPrompt(opts) {
  return RELATED_LINK_PROMPT_TEMPLATE.replace("{new_note_title}", opts.new_note_title).replace("{new_note_content}", opts.new_note_content).replace("{related_note_context}", opts.related_note_context).replace("{related_note_mode}", opts.related_note_mode);
}
async function recommendRelatedLinks(settings, opts) {
  const prompt = buildRelatedLinkPrompt(opts);
  return complete(settings, "Follow the user's instructions exactly.", prompt);
}
function estimateGenerateNoteTokens(opts) {
  var _a, _b, _c, _d, _e, _f, _g;
  const settings = opts.settings;
  const related = (_a = opts.related_notes) != null ? _a : [];
  const sourceGeneration = (_b = opts.source_generation) != null ? _b : true;
  const system = baseSystemPrompt(settings, sourceGeneration);
  const expectedOutput = settings.mode === "report" ? EXPECTED_NOTE_OUTPUT_TOKENS : EXPECTED_SUMMARY_OUTPUT_TOKENS;
  const promptOpts = {
    settings,
    source_label: opts.source_label,
    source_text: opts.source_text,
    user_prompt: (_c = opts.user_prompt) != null ? _c : "",
    related_notes: related,
    related_links: (_d = opts.related_links) != null ? _d : "",
    source_generation: sourceGeneration,
    source_url: (_e = opts.source_url) != null ? _e : "",
    content_type: (_f = opts.content_type) != null ? _f : "",
    question: (_g = opts.question) != null ? _g : "",
    snapshotContext: opts.snapshotContext
  };
  if (opts.source_text.length <= MERGE_THRESHOLD) {
    const user = buildUserPrompt(promptOpts);
    return [{
      label: "Main note generation",
      input_tokens: estimateMessagesTokens(system, user),
      output_tokens: expectedOutput,
      calls: 1
    }];
  }
  const chunks = chunkText(opts.source_text);
  const estimates = chunks.map((chunk, i) => {
    var _a2;
    const partialPrompt = `This is part ${i + 1}/${chunks.length} of a long source (${opts.source_label}). Produce a detailed partial analysis only.

# Source: ${opts.source_label}

${chunk}` + optionalInstructionsBlock((_a2 = opts.user_prompt) != null ? _a2 : "");
    return {
      label: `Long-source partial ${i + 1}/${chunks.length}`,
      input_tokens: estimateMessagesTokens(system, partialPrompt),
      output_tokens: EXPECTED_PARTIAL_OUTPUT_TOKENS,
      calls: 1
    };
  });
  let mergePrompt = noteOutputInstructions({
    source_generation: sourceGeneration,
    source_url: opts.source_url,
    content_type: opts.content_type,
    question: opts.question
  }) + "\n\nMerge partial analyses.\n\n" + chunks.map(() => "(estimated partial analysis output)").join("\n\n---\n\n");
  if (settings.toggles.compare_existing_notes && related.length) {
    mergePrompt += "\n\n" + buildUserPrompt({ ...promptOpts, source_text: "(see partials above)", user_prompt: "", include_output_instructions: false });
  }
  estimates.push({
    label: "Long-source merge",
    input_tokens: estimateMessagesTokens(system, mergePrompt),
    output_tokens: expectedOutput,
    calls: 1
  });
  return estimates;
}
function estimateSnapshotTokens(title, relative_path, body) {
  const prompt = buildSnapshotPrompt(title, relative_path, body);
  return {
    label: `Snapshot: ${title}`,
    input_tokens: estimateMessagesTokens("Follow the user's instructions exactly.", prompt),
    output_tokens: EXPECTED_SNAPSHOT_OUTPUT_TOKENS,
    calls: 1
  };
}

// src/fetchers/pdf.ts
var import_obsidian3 = require("obsidian");

// src/fetchers/base.ts
function makeResult(partial) {
  var _a, _b;
  return {
    metadata: (_a = partial.metadata) != null ? _a : {},
    warnings: (_b = partial.warnings) != null ? _b : [],
    content_type: partial.content_type,
    title: partial.title,
    text: partial.text,
    source_url: partial.source_url
  };
}

// src/fetchers/pdf.ts
var MAX_PDF_BYTES = 50 * 1024 * 1024;
function extractTextFromPdfBytes(bytes) {
  var _a;
  const raw = new Uint8Array(bytes);
  const decoder = new TextDecoder("latin1");
  const content = decoder.decode(raw);
  const pageMatches = content.match(/\/Type\s*\/Page\b/g);
  const pageCount = (_a = pageMatches == null ? void 0 : pageMatches.length) != null ? _a : 1;
  const textChunks = [];
  const streamRe = /stream\r?\n([\s\S]*?)\r?\nendstream/g;
  let match;
  while ((match = streamRe.exec(content)) !== null) {
    const stream = match[1];
    const tjMatches = stream.match(/\((?:\\.|[^\\)])*\)\s*Tj/g);
    if (tjMatches) {
      for (const tj of tjMatches) {
        const inner = tj.replace(/\)\s*Tj$/, "").slice(1);
        const decoded = inner.replace(/\\n/g, "\n").replace(/\\r/g, "\r").replace(/\\t/g, "	").replace(/\\\(/g, "(").replace(/\\\)/g, ")").replace(/\\\\/g, "\\");
        if (decoded.trim()) textChunks.push(decoded);
      }
    }
  }
  const text = textChunks.join(" ").replace(/\s+/g, " ").trim();
  if (!text) {
    throw new Error("PDF contains no extractable text (scanned PDFs are not yet supported).");
  }
  return { text, pageCount };
}
async function fetchPdf(source, app) {
  var _a, _b;
  let bytes;
  let title = "PDF";
  const warnings = [];
  if (source.startsWith("http://") || source.startsWith("https://")) {
    const resp = await (0, import_obsidian3.requestUrl)({ url: source, method: "GET" });
    if (resp.status >= 400) throw new Error(`PDF download failed (${resp.status}).`);
    bytes = resp.arrayBuffer;
    if (bytes.byteLength > MAX_PDF_BYTES) throw new Error("PDF exceeds 50 MB limit.");
    try {
      title = decodeURIComponent((_b = (_a = new URL(source).pathname.split("/").pop()) == null ? void 0 : _a.replace(/\.pdf$/i, "")) != null ? _b : "Online PDF");
    } catch (e) {
      title = "Online PDF";
    }
  } else {
    if (!app) throw new Error("Vault PDF paths require the Obsidian app context.");
    const normalized = source.replace(/^\/+/, "");
    const file = app.vault.getAbstractFileByPath(normalized);
    if (!(file instanceof import_obsidian3.TFile) || file.extension !== "pdf") {
      throw new Error(`PDF not found in vault: ${source}`);
    }
    bytes = await app.vault.readBinary(file);
    title = file.basename;
  }
  const { text, pageCount } = extractTextFromPdfBytes(bytes);
  return makeResult({
    content_type: "pdf",
    title,
    text,
    source_url: source,
    metadata: { page_count: pageCount },
    warnings
  });
}

// src/fetchers/reddit.ts
var import_obsidian4 = require("obsidian");
var POST_JSON_RE = /\/r\/([^/]+)\/comments\/([^/]+)/;
function submissionJsonUrl(url) {
  const m = url.match(POST_JSON_RE);
  if (!m) throw new Error("Not a valid Reddit post URL.");
  return `https://www.reddit.com/r/${m[1]}/comments/${m[2]}.json`;
}
async function fetchReddit(url, maxComments = 30) {
  var _a, _b, _c, _d, _e, _f, _g, _h, _i, _j, _k, _l, _m, _n;
  const jsonUrl = submissionJsonUrl(url);
  const resp = await (0, import_obsidian4.requestUrl)({
    url: jsonUrl,
    method: "GET",
    headers: { "User-Agent": "insider:v1.0 (research tool)" }
  });
  if (resp.status === 404) throw new Error("Reddit post not found or is private.");
  if (resp.status >= 400) throw new Error(`Reddit fetch failed (${resp.status}).`);
  const data = resp.json;
  const postData = (_e = (_d = (_c = (_b = (_a = data[0]) == null ? void 0 : _a.data) == null ? void 0 : _b.children) == null ? void 0 : _c[0]) == null ? void 0 : _d.data) != null ? _e : {};
  const title = String((_f = postData.title) != null ? _f : "Reddit post");
  const selftext = String((_g = postData.selftext) != null ? _g : "").trim();
  const author = String((_h = postData.author) != null ? _h : "unknown");
  const subreddit = String((_i = postData.subreddit) != null ? _i : "");
  const lines = [
    `# ${title}`,
    `**Subreddit:** r/${subreddit}  **Author:** u/${author}`,
    "",
    selftext || "_(link post \u2014 see source URL)_"
  ];
  const comments = (_l = (_k = (_j = data[1]) == null ? void 0 : _j.data) == null ? void 0 : _k.children) != null ? _l : [];
  const commentLines = [];
  let count = 0;
  for (const child of comments) {
    if (child.kind !== "t1") continue;
    const c = child.data;
    const body = String((_m = c.body) != null ? _m : "").trim();
    if (!body || body === "[deleted]" || body === "[removed]") continue;
    commentLines.push(`**u/${String((_n = c.author) != null ? _n : "?")}:** ${body}`);
    count++;
    if (count >= maxComments) break;
  }
  if (commentLines.length) {
    lines.push("", "## Top comments", "", ...commentLines);
  }
  const warnings = [];
  if (count >= maxComments) warnings.push(`Comment list capped at ${maxComments}.`);
  return makeResult({
    content_type: "reddit",
    title,
    text: lines.join("\n"),
    source_url: url,
    metadata: { subreddit, comment_count: count },
    warnings
  });
}

// src/fetchers/twitter.ts
var import_obsidian5 = require("obsidian");
var STATUS_RE = /\/status\/(\d+)/;
function extractTweetId(url) {
  try {
    const m = new URL(url).pathname.match(STATUS_RE);
    if (m) return m[1];
  } catch (e) {
  }
  throw new Error("Not a valid X/Twitter status URL.");
}
async function fetchTwitter(url, bearerToken) {
  var _a, _b, _c, _d, _e, _f, _g, _h, _i, _j;
  if (!bearerToken.trim()) {
    throw new Error("X/Twitter requires a bearer token in Insider settings.");
  }
  const tweetId = extractTweetId(url);
  const headers = { Authorization: `Bearer ${bearerToken}` };
  const params = new URLSearchParams({
    "tweet.fields": "created_at,author_id,conversation_id",
    expansions: "author_id",
    "user.fields": "username,name"
  });
  const resp = await (0, import_obsidian5.requestUrl)({
    url: `https://api.twitter.com/2/tweets/${tweetId}?${params}`,
    method: "GET",
    headers
  });
  if (resp.status === 401) throw new Error("Invalid Twitter bearer token.");
  if (resp.status >= 400) throw new Error(`Twitter API error (${resp.status}).`);
  const payload = resp.json;
  const tweet = (_a = payload.data) != null ? _a : {};
  const users = Object.fromEntries(((_c = (_b = payload.includes) == null ? void 0 : _b.users) != null ? _c : []).map((u) => [u.id, u]));
  const author = (_e = users[(_d = tweet.author_id) != null ? _d : ""]) != null ? _e : {};
  const handle = (_f = author.username) != null ? _f : "unknown";
  const lines = [`**@${handle}** (${(_g = tweet.created_at) != null ? _g : ""})`, "", (_h = tweet.text) != null ? _h : ""];
  const warnings = [];
  const conversationId = tweet.conversation_id;
  if (conversationId && conversationId !== tweetId) {
    try {
      const threadResp = await (0, import_obsidian5.requestUrl)({
        url: `https://api.twitter.com/2/tweets/search/recent?${new URLSearchParams({
          query: `conversation_id:${conversationId} from:${handle}`,
          "tweet.fields": "created_at",
          max_results: "20"
        })}`,
        method: "GET",
        headers
      });
      if (threadResp.status === 200) {
        const threadData = (_i = threadResp.json.data) != null ? _i : [];
        if (threadData.length > 1) {
          lines.push("", "## Thread");
          for (const t of [...threadData].sort((a, b) => {
            var _a2, _b2;
            return ((_a2 = a.created_at) != null ? _a2 : "").localeCompare((_b2 = b.created_at) != null ? _b2 : "");
          })) {
            if (t.id === tweetId) continue;
            lines.push((_j = t.text) != null ? _j : "", "");
          }
        }
      } else {
        warnings.push("Could not expand full thread (API tier limits may apply).");
      }
    } catch (e) {
      warnings.push("Could not expand full thread.");
    }
  }
  return makeResult({
    content_type: "twitter",
    title: `@${handle} tweet`,
    text: lines.join("\n").trim(),
    source_url: url,
    metadata: { tweet_id: tweetId, author: handle },
    warnings
  });
}

// src/fetchers/youtube.ts
var import_obsidian6 = require("obsidian");
var AUDIO_CUE_RE = /\[(?:music|applause|laughter|silence)\]/gi;
var ANDROID_UA = "com.google.android.youtube/20.10.38 (Linux; U; Android 14) gzip";
var BROWSER_UA = "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36";
var PREFERRED_LANGS = ["en", "en-US", "en-GB", "en-CA", "en-AU"];
function extractVideoId(url) {
  try {
    const parsed = new URL(url);
    if (parsed.hostname === "youtu.be") {
      const id = parsed.pathname.slice(1).split("/")[0];
      if (id) return id;
    }
    if (parsed.hostname.includes("youtube")) {
      if (parsed.pathname === "/watch") {
        const id = parsed.searchParams.get("v");
        if (id) return id;
      }
      if (parsed.pathname.startsWith("/shorts/")) {
        const id = parsed.pathname.split("/")[2];
        if (id) return id;
      }
      if (parsed.pathname.startsWith("/embed/")) {
        const id = parsed.pathname.split("/")[2];
        if (id) return id;
      }
    }
  } catch (e) {
  }
  throw new Error("Not a valid YouTube URL.");
}
function formatTime(seconds) {
  const total = Math.floor(seconds);
  const h = Math.floor(total / 3600);
  const m = Math.floor(total % 3600 / 60);
  const s = total % 60;
  if (h) return `${h}:${String(m).padStart(2, "0")}:${String(s).padStart(2, "0")}`;
  return `${m}:${String(s).padStart(2, "0")}`;
}
function unescapeYoutubeUrl(url) {
  return url.replace(/\\u0026/g, "&").replace(/\\\//g, "/");
}
function captionTracksFromPlayer(player) {
  var _a;
  const captions = player.captions;
  const renderer = captions == null ? void 0 : captions.playerCaptionsTracklistRenderer;
  return (_a = renderer == null ? void 0 : renderer.captionTracks) != null ? _a : [];
}
function extractJsonObject(html, start) {
  const open = html.indexOf("{", start);
  if (open < 0) return null;
  let depth = 0;
  for (let i = open; i < html.length; i++) {
    const ch = html[i];
    if (ch === "{") depth++;
    else if (ch === "}") {
      depth--;
      if (depth === 0) return html.slice(open, i + 1);
    }
  }
  return null;
}
function parsePlayerResponseFromHtml(html) {
  const markers = ["ytInitialPlayerResponse", "var ytInitialPlayerResponse"];
  for (const marker of markers) {
    const idx = html.indexOf(marker);
    if (idx < 0) continue;
    const jsonStr = extractJsonObject(html, idx);
    if (!jsonStr) continue;
    try {
      return JSON.parse(jsonStr);
    } catch (e) {
      continue;
    }
  }
  return null;
}
function captionTracksFromHtml(html) {
  const player = parsePlayerResponseFromHtml(html);
  if (player) {
    const tracks = captionTracksFromPlayer(player);
    if (tracks.length) return tracks;
  }
  const label = '"captionTracks":';
  const idx = html.indexOf(label);
  if (idx < 0) return [];
  const arrStart = html.indexOf("[", idx + label.length);
  if (arrStart < 0) return [];
  let depth = 0;
  for (let i = arrStart; i < html.length; i++) {
    const ch = html[i];
    if (ch === "[") depth++;
    else if (ch === "]") {
      depth--;
      if (depth === 0) {
        try {
          return JSON.parse(html.slice(arrStart, i + 1));
        } catch (e) {
          return [];
        }
      }
    }
  }
  return [];
}
function pickCaptionTrack(tracks) {
  var _a;
  if (!tracks.length) return null;
  for (const lang of PREFERRED_LANGS) {
    const match = tracks.find((t) => t.languageCode === lang);
    if (match == null ? void 0 : match.baseUrl) return match;
  }
  const manual = tracks.find((t) => t.kind !== "asr" && t.baseUrl);
  if (manual) return manual;
  return (_a = tracks.find((t) => t.baseUrl)) != null ? _a : null;
}
function decodeTranscriptXml(xml) {
  const segments = [];
  const re = /<text start="([^"]+)"[^>]*>([\s\S]*?)<\/text>/g;
  let match;
  while ((match = re.exec(xml)) !== null) {
    const start = parseFloat(match[1]);
    const text = match[2].replace(/&amp;/g, "&").replace(/&lt;/g, "<").replace(/&gt;/g, ">").replace(/&quot;/g, '"').replace(/&#39;/g, "'").replace(/<[^>]+>/g, "").trim();
    if (text) segments.push({ start, text });
  }
  return segments;
}
function decodeTranscriptJson3(json) {
  var _a, _b, _c;
  const data = JSON.parse(json);
  const segments = [];
  for (const event of (_a = data.events) != null ? _a : []) {
    const text = ((_b = event.segs) != null ? _b : []).map((s) => {
      var _a2;
      return (_a2 = s.utf8) != null ? _a2 : "";
    }).join("").replace(/\n/g, " ").trim();
    if (!text) continue;
    segments.push({ start: ((_c = event.tStartMs) != null ? _c : 0) / 1e3, text });
  }
  return segments;
}
async function innertubePlayerRequest(videoId, client, apiKey) {
  const url = client === "WEB" && apiKey ? `https://www.youtube.com/youtubei/v1/player?key=${apiKey}&prettyPrint=false` : "https://www.youtube.com/youtubei/v1/player?prettyPrint=false";
  const clientVersion = client === "ANDROID" ? "20.10.38" : "2.20241120.01.00";
  const headers = {
    "Content-Type": "application/json",
    Accept: "*/*",
    "Accept-Language": "en-US,en;q=0.9"
  };
  if (client === "ANDROID") {
    headers["User-Agent"] = ANDROID_UA;
    headers["X-YouTube-Client-Name"] = "3";
    headers["X-YouTube-Client-Version"] = clientVersion;
  } else {
    headers["User-Agent"] = BROWSER_UA;
    headers["X-YouTube-Client-Name"] = "1";
    headers["X-YouTube-Client-Version"] = clientVersion;
  }
  const body = {
    context: {
      client: {
        clientName: client,
        clientVersion,
        hl: "en",
        gl: "US",
        ...client === "ANDROID" ? { androidSdkVersion: 34 } : {}
      }
    },
    videoId
  };
  const resp = await (0, import_obsidian6.requestUrl)({
    url,
    method: "POST",
    contentType: "application/json",
    headers,
    body: JSON.stringify(body),
    throw: false
  });
  if (resp.status >= 400) {
    throw new Error(`Innertube player request failed (${resp.status}).`);
  }
  return resp.json;
}
async function fetchInnertubeApiKey() {
  var _a, _b;
  const resp = await (0, import_obsidian6.requestUrl)({
    url: "https://www.youtube.com/embed/dQw4w9WgXcQ",
    method: "GET",
    headers: { "User-Agent": BROWSER_UA, "Accept-Language": "en-US,en;q=0.9" }
  });
  const html = (_a = resp.text) != null ? _a : "";
  const match = html.match(/"INNERTUBE_API_KEY":"([^"]+)"/);
  return (_b = match == null ? void 0 : match[1]) != null ? _b : null;
}
async function fetchCaptionTracks(videoId) {
  const errors = [];
  function playabilityHint(player) {
    const ps = player.playabilityStatus;
    if (!(ps == null ? void 0 : ps.status)) return "";
    return ` (playability: ${ps.status}${ps.reason ? ` \u2014 ${ps.reason}` : ""})`;
  }
  try {
    const player = await innertubePlayerRequest(videoId, "ANDROID");
    const tracks = captionTracksFromPlayer(player);
    if (tracks.length) return tracks;
    errors.push(`ANDROID innertube: no caption tracks${playabilityHint(player)}`);
  } catch (e) {
    errors.push(`ANDROID innertube: ${e instanceof Error ? e.message : String(e)}`);
  }
  try {
    const apiKey = await fetchInnertubeApiKey();
    if (apiKey) {
      const player = await innertubePlayerRequest(videoId, "WEB", apiKey);
      const tracks = captionTracksFromPlayer(player);
      if (tracks.length) return tracks;
      errors.push(`WEB innertube: no caption tracks${playabilityHint(player)}`);
    }
  } catch (e) {
    errors.push(`WEB innertube: ${e instanceof Error ? e.message : String(e)}`);
  }
  try {
    const resp = await (0, import_obsidian6.requestUrl)({
      url: `https://www.youtube.com/watch?v=${videoId}&hl=en`,
      method: "GET",
      headers: { "User-Agent": BROWSER_UA, "Accept-Language": "en-US,en;q=0.9" }
    });
    if (resp.status < 400 && resp.text) {
      const tracks = captionTracksFromHtml(resp.text);
      if (tracks.length) return tracks;
      errors.push("HTML scrape: no caption tracks found");
    }
  } catch (e) {
    errors.push(`HTML scrape: ${e instanceof Error ? e.message : String(e)}`);
  }
  console.warn("Insider YouTube caption lookup failed:", errors.join("; "));
  return [];
}
function captionJson3Url(baseUrl) {
  const clean = unescapeYoutubeUrl(baseUrl).replace(/&fmt=[^&]+/g, "");
  const joiner = clean.includes("?") ? "&" : "?";
  return `${clean}${joiner}fmt=json3`;
}
async function fetchTranscriptSegments(track) {
  var _a;
  const baseUrl = unescapeYoutubeUrl((_a = track.baseUrl) != null ? _a : "");
  if (!baseUrl) throw new Error("Caption track has no URL.");
  const isGenerated = track.kind === "asr";
  const headers = { "User-Agent": BROWSER_UA, "Accept-Language": "en-US,en;q=0.9" };
  const jsonUrl = captionJson3Url(baseUrl);
  try {
    const jsonResp = await (0, import_obsidian6.requestUrl)({ url: jsonUrl, method: "GET", headers });
    if (jsonResp.status === 200 && jsonResp.text.includes('"events"')) {
      const segments2 = decodeTranscriptJson3(jsonResp.text);
      if (segments2.length) return { segments: segments2, isGenerated };
    }
  } catch (e) {
  }
  const xmlResp = await (0, import_obsidian6.requestUrl)({ url: baseUrl, method: "GET", headers });
  if (xmlResp.status >= 400) {
    throw new Error(`Caption download failed (${xmlResp.status}).`);
  }
  const segments = decodeTranscriptXml(xmlResp.text);
  if (!segments.length) {
    throw new Error("Could not parse YouTube transcript (empty caption file).");
  }
  return { segments, isGenerated };
}
async function fetchYoutube(url, opts = {}) {
  var _a, _b, _c;
  const videoId = extractVideoId(url);
  const warnings = [];
  const includeTimestamps = (_a = opts.include_timestamps) != null ? _a : true;
  const stripAudioCues = (_b = opts.strip_audio_cues) != null ? _b : true;
  const tracks = await fetchCaptionTracks(videoId);
  const track = pickCaptionTrack(tracks);
  if (!track) {
    throw new Error(
      "No captions available for this video. YouTube may be blocking the request, or the video has no captions."
    );
  }
  const { segments, isGenerated } = await fetchTranscriptSegments(track);
  if (isGenerated) {
    warnings.push("Using auto-generated captions (no manual track found).");
  } else {
    warnings.push(`Using ${(_c = track.languageCode) != null ? _c : "available"} captions.`);
  }
  const lines = [];
  for (const seg of segments) {
    let text = seg.text;
    if (stripAudioCues) text = text.replace(AUDIO_CUE_RE, "").trim();
    if (!text) continue;
    lines.push(includeTimestamps ? `[${formatTime(seg.start)}] ${text}` : text);
  }
  const body = lines.join("\n");
  if (!body) throw new Error("Transcript was empty after cleaning.");
  return makeResult({
    content_type: "youtube",
    title: `YouTube ${videoId}`,
    text: body,
    source_url: url,
    metadata: { video_id: videoId, segment_count: segments.length, language: track.languageCode },
    warnings
  });
}

// src/fetchers/router.ts
var YOUTUBE_RE = /(youtube\.com|youtu\.be)/i;
var REDDIT_RE = /(reddit\.com|redd\.it)/i;
var TWITTER_RE = /(twitter\.com|x\.com)/i;
function detectSource(source) {
  var _a;
  const trimmed = source.trim();
  if (trimmed.toLowerCase().endsWith(".pdf") || trimmed.startsWith("/") || trimmed.startsWith("~")) {
    try {
      const parsed = new URL(trimmed.startsWith("http") ? trimmed : `file://${trimmed}`);
      if (parsed.protocol.startsWith("http") && parsed.pathname.toLowerCase().includes(".pdf")) return "pdf_url";
    } catch (e) {
    }
    if (!trimmed.startsWith("http")) return "pdf_file";
  }
  let host = "";
  try {
    host = (_a = new URL(trimmed).hostname) != null ? _a : "";
  } catch (e) {
    if (trimmed.toLowerCase().endsWith(".pdf")) return "pdf_file";
  }
  if (YOUTUBE_RE.test(host)) return "youtube";
  if (REDDIT_RE.test(host)) return "reddit";
  if (TWITTER_RE.test(host)) return "twitter";
  try {
    if (new URL(trimmed).pathname.toLowerCase().endsWith(".pdf")) return "pdf_url";
  } catch (e) {
  }
  throw new Error(`Unsupported source: ${source}`);
}
async function fetchSource(source, settings, app) {
  const kind = detectSource(source);
  switch (kind) {
    case "youtube":
      return fetchYoutube(source, {
        include_timestamps: settings.toggles.include_timestamps,
        strip_audio_cues: settings.toggles.strip_audio_cues
      });
    case "reddit":
      return fetchReddit(source, settings.reddit_max_comments);
    case "twitter":
      return fetchTwitter(source, settings.twitter_bearer_token);
    case "pdf_file":
    case "pdf_url":
      return fetchPdf(source, app);
    default:
      throw new Error(`Unhandled source type: ${kind}`);
  }
}

// src/memory/snapshots.ts
function listSnapshots(snapshots) {
  return snapshots;
}
function hasSnapshots(snapshots) {
  return snapshots.length > 0;
}
function vaultSnapshotText(snapshots) {
  return snapshots.filter((s) => s.summary.trim()).map((s) => s.summary).join("\n");
}
function snapshotsAsContext(snapshots) {
  if (!snapshots.length) return "";
  const lines = ["## Vault memory (snapshots of existing notes)"];
  for (const s of snapshots) {
    lines.push(`### [[${s.title}]] (${s.relative_path})`);
    lines.push(s.summary);
    lines.push("");
  }
  return lines.join("\n");
}
function replaceSnapshots(items) {
  const now = (/* @__PURE__ */ new Date()).toISOString();
  return items.map((item) => ({
    relative_path: item.relative_path,
    title: item.title,
    summary: item.summary,
    updated_at: now
  }));
}
function upsertSnapshot(snapshots, relative_path, title, summary) {
  const now = (/* @__PURE__ */ new Date()).toISOString();
  const idx = snapshots.findIndex((s) => s.relative_path === relative_path);
  if (idx >= 0) {
    const updated = [...snapshots];
    updated[idx] = { relative_path, title, summary, updated_at: now };
    return updated;
  }
  return [...snapshots, { relative_path, title, summary, updated_at: now }];
}

// src/vault/notes.ts
var import_obsidian7 = require("obsidian");
var FRONTMATTER_RE = /^---\s*\n[\s\S]*?\n---\s*\n/;
var NOTE_TITLE_RE = /^NOTE_TITLE:\s*(.+?)(?:\r?\n|$)/m;
var INVALID_FILENAME_CHARS = /[\\/:*?"<>|]/g;
var ATTACHMENT_DIR_NAMES = /* @__PURE__ */ new Set(["0attachments", "attachments", "assets", "images"]);
var IMAGE_EMBED_RE = /!\[\[[^\]]+\.(?:png|jpe?g|gif|webp|heic|svg)\]\]|!\[[^\]]*\]\([^)]+\.(?:png|jpe?g|gif|webp|heic|svg)\)/gi;
function stripFrontmatter(text) {
  return text.replace(FRONTMATTER_RE, "").trim();
}
function isAttachmentPath(relativePath) {
  const parts = relativePath.split("/");
  return parts.slice(0, -1).some((p) => ATTACHMENT_DIR_NAMES.has(p.toLowerCase()));
}
function isImageOnlyNote(body) {
  const withoutEmbeds = body.replace(IMAGE_EMBED_RE, "");
  const withoutComments = withoutEmbeds.replace(/%%[\s\S]*?%%/g, "");
  return Boolean(body.trim()) && !withoutComments.trim();
}
function titleFromFile(file, raw) {
  const fmMatch = raw.match(/^title:\s*(.+)$/m);
  if (fmMatch) return fmMatch[1].trim();
  return file.basename;
}
async function listNotes(app, opts = {}) {
  var _a, _b;
  const limit = (_a = opts.limit) != null ? _a : 500;
  const bodyLimit = (_b = opts.bodyLimit) != null ? _b : 4e3;
  const files = app.vault.getMarkdownFiles().sort((a, b) => a.path.localeCompare(b.path));
  const notes = [];
  for (const file of files) {
    if (file.path.split("/").some((p) => p.startsWith("."))) continue;
    if (opts.excludeAttachmentNotes && isAttachmentPath(file.path)) continue;
    const raw = await app.vault.cachedRead(file);
    let body = stripFrontmatter(raw);
    if (opts.excludeAttachmentNotes && isImageOnlyNote(body)) continue;
    if (bodyLimit !== null) body = body.slice(0, bodyLimit);
    notes.push({
      path: file.path,
      title: titleFromFile(file, raw),
      body,
      relative_path: file.path
    });
    if (limit !== null && notes.length >= limit) break;
  }
  return notes;
}
function findRelatedNotes(notes, query, limit = 5) {
  var _a;
  const words = new Set(((_a = query.match(/\w{4,}/g)) != null ? _a : []).map((w) => w.toLowerCase()));
  if (!words.size) return [];
  const scored = [];
  for (const note of notes.slice(0, 300)) {
    const hay = `${note.title} ${note.body}`.toLowerCase();
    let score = 0;
    for (const w of words) {
      if (hay.includes(w)) score++;
    }
    if (score) scored.push({ score, note });
  }
  scored.sort((a, b) => b.score - a.score);
  return scored.slice(0, limit).map((s) => s.note);
}
function sanitizeFilename(title) {
  const cleaned = title.replace(INVALID_FILENAME_CHARS, "").trim().replace(/\s+/g, " ");
  return cleaned.slice(0, 120) || "Untitled";
}
function parseGeneratedNote(text, fallbackTitle = "Untitled") {
  let raw = text.trim();
  let title = fallbackTitle;
  const match = raw.match(NOTE_TITLE_RE);
  if (match) {
    title = sanitizeFilename(match[1].trim()) || fallbackTitle;
    raw = raw.slice(match.index + match[0].length).replace(/^\r?\n/, "");
  }
  if (raw.startsWith("# ")) {
    const firstLine = raw.split("\n", 1)[0].slice(2).trim();
    if (firstLine.toLowerCase() === title.toLowerCase()) {
      raw = raw.includes("\n") ? raw.split("\n").slice(1).join("\n").replace(/^\r?\n/, "") : "";
    }
  }
  return { title, content: raw };
}
async function uniquePath(app, folder, basename) {
  let candidate = (0, import_obsidian7.normalizePath)(`${folder}/${basename}.md`);
  let n = 2;
  while (app.vault.getAbstractFileByPath(candidate)) {
    candidate = (0, import_obsidian7.normalizePath)(`${folder}/${basename} (${n}).md`);
    n++;
  }
  return candidate;
}
async function writeNote(app, outputFolder, title, body) {
  const folder = (0, import_obsidian7.normalizePath)(outputFolder.trim() || "To-Process");
  const folderExists = app.vault.getAbstractFileByPath(folder);
  if (!folderExists) {
    await app.vault.createFolder(folder);
  }
  const parsed = parseGeneratedNote(body, title);
  const filePath = await uniquePath(app, folder, parsed.title);
  await app.vault.create(filePath, parsed.content.trimEnd() + "\n");
  return { path: filePath, title: parsed.title };
}

// src/related/index.ts
var RELATED_LINE_RE = /^-\s*\[\[(?<title>[^\]]+)\]\]\s*\|\s*Lens:\s*(?<lens>[^|]+)\|\s*Reason:\s*(?<reason>.+)$/;
var SNAPSHOT_TITLE_RE = /^##\s+\[\[(?<title>[^\]]+)\]\]\s*$/gm;
function normalizeTitle(title) {
  return title.trim().split(/\s+/).join(" ");
}
function snapshotTitles(vaultSnapshot) {
  var _a;
  const titles = /* @__PURE__ */ new Set();
  let match;
  const re = new RegExp(SNAPSHOT_TITLE_RE.source, SNAPSHOT_TITLE_RE.flags);
  while ((match = re.exec(vaultSnapshot)) !== null) {
    if ((_a = match.groups) == null ? void 0 : _a.title) titles.add(normalizeTitle(match.groups.title));
  }
  return titles;
}
function parseRelatedRecommendations(text) {
  const parsed = [];
  for (const line of text.split("\n")) {
    const match = line.trim().match(RELATED_LINE_RE);
    if (!(match == null ? void 0 : match.groups)) continue;
    const title = normalizeTitle(match.groups.title);
    const lens = match.groups.lens.trim();
    const reason = match.groups.reason.trim();
    if (title) parsed.push([title, lens, reason]);
  }
  return parsed;
}
function validateRelatedRecommendations(recommendations, vaultNotes, vaultSnapshot) {
  const notesByTitle = /* @__PURE__ */ new Map();
  for (const note of vaultNotes) {
    if (note.title.trim()) notesByTitle.set(normalizeTitle(note.title), note);
  }
  const snapTitles = snapshotTitles(vaultSnapshot);
  const validated = [];
  const warnings = [];
  const seen = /* @__PURE__ */ new Set();
  for (const [title, lens, reason] of recommendations) {
    if (!title) {
      warnings.push("Dropped an empty related-note recommendation.");
      continue;
    }
    if (seen.has(title)) continue;
    const note = notesByTitle.get(title);
    if (!note) {
      warnings.push(`Dropped nonexistent related-note recommendation: [[${title}]]`);
      continue;
    }
    if (snapTitles.size && !snapTitles.has(title)) {
      warnings.push(`Dropped recommendation not present in vault snapshot: [[${title}]]`);
      continue;
    }
    validated.push({ title, lens, reason, note });
    seen.add(title);
  }
  return { validated, warnings };
}
function candidateNotesContext(notes) {
  const blocks = [];
  for (const note of notes) {
    blocks.push(`## [[${note.title}]]`);
    blocks.push(`Path: ${note.relative_path}`);
    blocks.push(note.body.slice(0, 2500));
    blocks.push("");
  }
  return blocks.join("\n");
}
function formatValidatedRecommendations(recommendations) {
  if (!recommendations.length) return "";
  const lines = ["Related notes:"];
  for (const item of recommendations) {
    lines.push(`- [[${item.title}]] | Lens: ${item.lens} | Reason: ${item.reason}`);
  }
  return lines.join("\n");
}
function estimateRelatedLookupTokens(snapshots, new_note_title, new_note_content) {
  if (!hasSnapshots(snapshots)) {
    return { estimate: null, warnings: ["No snapshots found. Refresh semantic snapshots before snapshot-based linking."] };
  }
  const vaultSnapshot = vaultSnapshotText(snapshots);
  if (!vaultSnapshot.trim()) {
    return { estimate: null, warnings: ["Snapshots exist but contain no usable note snapshots."] };
  }
  const prompt = buildRelatedLinkPrompt({
    new_note_title,
    new_note_content,
    related_note_context: vaultSnapshot,
    related_note_mode: "snapshot"
  });
  return {
    estimate: {
      label: "Snapshot related-note lookup",
      input_tokens: estimateMessagesTokens("Follow the user's instructions exactly.", prompt),
      output_tokens: EXPECTED_RELATED_LINK_OUTPUT_TOKENS,
      calls: 1
    },
    warnings: []
  };
}
function estimateKeywordRelatedLookupTokens(new_note_title, new_note_content, candidate_notes) {
  if (!candidate_notes.length) return null;
  const prompt = buildRelatedLinkPrompt({
    new_note_title,
    new_note_content,
    related_note_context: candidateNotesContext(candidate_notes),
    related_note_mode: "keyword"
  });
  return {
    label: "Keyword related-note lens mapping",
    input_tokens: estimateMessagesTokens("Follow the user's instructions exactly.", prompt),
    output_tokens: EXPECTED_RELATED_LINK_OUTPUT_TOKENS,
    calls: 1
  };
}
async function discoverRelatedNotesFromSnapshot(app, settings, snapshots, new_note_title, new_note_content) {
  if (!hasSnapshots(snapshots)) {
    return { notes: [], warnings: ["No snapshots found. Refresh semantic snapshots before snapshot-based linking."], links: "" };
  }
  const vaultSnapshot = vaultSnapshotText(snapshots);
  if (!vaultSnapshot.trim()) {
    return { notes: [], warnings: ["Snapshots exist but contain no usable note snapshots."], links: "" };
  }
  const raw = await recommendRelatedLinks(settings, {
    new_note_title,
    new_note_content,
    related_note_context: vaultSnapshot,
    related_note_mode: "snapshot"
  });
  const parsed = parseRelatedRecommendations(raw);
  const vaultNotes = await listNotes(app, { limit: null, bodyLimit: null });
  const { validated, warnings } = validateRelatedRecommendations(parsed, vaultNotes, vaultSnapshot);
  const limited = validated.slice(0, settings.max_related_notes);
  return {
    notes: limited.map((v) => v.note),
    warnings,
    links: formatValidatedRecommendations(limited)
  };
}
async function discoverRelatedNotesFromKeyword(settings, new_note_title, new_note_content, candidate_notes) {
  if (!candidate_notes.length) return { notes: [], warnings: [], links: "" };
  const raw = await recommendRelatedLinks(settings, {
    new_note_title,
    new_note_content,
    related_note_context: candidateNotesContext(candidate_notes),
    related_note_mode: "keyword"
  });
  const parsed = parseRelatedRecommendations(raw);
  const { validated, warnings } = validateRelatedRecommendations(parsed, candidate_notes, "");
  const limited = validated.slice(0, settings.max_related_notes);
  return {
    notes: limited.map((v) => v.note),
    warnings,
    links: formatValidatedRecommendations(limited)
  };
}

// src/engine/pipeline.ts
function titleFromResult(result, userPrompt) {
  if (result.title && !result.title.startsWith("YouTube")) return result.title.slice(0, 80);
  if (userPrompt.trim()) return userPrompt.slice(0, 60).trim() || result.title.slice(0, 80);
  return result.title.slice(0, 80) || "Untitled";
}
async function relatedForNewNote(app, settings, snapshots, title, content, allNotes) {
  if (!settings.toggles.compare_existing_notes) {
    return { notes: [], warnings: [], links: "" };
  }
  if (settings.related_notes_mode === "keyword") {
    const candidates = findRelatedNotes(allNotes, content, settings.max_related_notes);
    return discoverRelatedNotesFromKeyword(settings, title, content, candidates);
  }
  return discoverRelatedNotesFromSnapshot(app, settings, snapshots, title, content);
}
async function relatedLookupEstimates(app, settings, snapshots, title, content, allNotes) {
  if (!settings.toggles.compare_existing_notes) return { estimates: [], warnings: [] };
  if (settings.related_notes_mode === "keyword") {
    const candidates = findRelatedNotes(allNotes, content, settings.max_related_notes);
    const estimate2 = estimateKeywordRelatedLookupTokens(title, content, candidates);
    return { estimates: estimate2 ? [estimate2] : [], warnings: [] };
  }
  const { estimate, warnings } = estimateRelatedLookupTokens(snapshots, title, content);
  return { estimates: estimate ? [estimate] : [], warnings };
}
async function processSource(app, settings, snapshots, source, userPrompt = "", onTokenEstimate) {
  try {
    const fetched = await fetchSource(source, settings, app);
    const title = titleFromResult(fetched, userPrompt);
    const relatedContent = `${fetched.title}

${fetched.text.slice(0, 8e3)}

${userPrompt}`;
    const allNotes = await listNotes(app, { limit: 300 });
    if (settings.toggles.estimate_token_usage && onTokenEstimate) {
      const { estimates } = await relatedLookupEstimates(app, settings, snapshots, title, relatedContent, allNotes);
      if (estimates.length) onTokenEstimate(estimates);
    }
    const { notes: related, warnings: relatedWarnings, links: relatedLinks } = await relatedForNewNote(
      app,
      settings,
      snapshots,
      title,
      relatedContent,
      allNotes
    );
    const snapshotContext = snapshotsAsContext(snapshots);
    if (settings.toggles.estimate_token_usage && onTokenEstimate) {
      onTokenEstimate(
        estimateGenerateNoteTokens({
          settings,
          source_label: fetched.title,
          source_text: fetched.text,
          user_prompt: userPrompt,
          related_notes: related,
          related_links: relatedLinks,
          source_url: fetched.source_url,
          content_type: fetched.content_type,
          snapshotContext
        })
      );
    }
    const { body, warnings: aiWarnings } = await generateNote({
      settings,
      source_label: fetched.title,
      source_text: fetched.text,
      user_prompt: userPrompt,
      related_notes: related,
      related_links: relatedLinks,
      source_url: fetched.source_url,
      content_type: fetched.content_type,
      snapshotContext
    });
    const written = await writeNote(app, settings.output_folder, title, body);
    let updatedSnapshots = snapshots;
    for (const note of related) {
      const summary = await summarizeForSnapshot(settings, note.title, note.relative_path, note.body);
      updatedSnapshots = upsertSnapshot(updatedSnapshots, note.relative_path, note.title, summary);
    }
    return {
      ok: true,
      path: written.path,
      title: written.title,
      warnings: [...fetched.warnings, ...relatedWarnings, ...aiWarnings],
      content_type: fetched.content_type,
      updatedSnapshots
    };
  } catch (e) {
    return { ok: false, error: e instanceof Error ? e.message : String(e) };
  }
}
async function processQuestion(app, settings, snapshots, question, onTokenEstimate) {
  var _a;
  try {
    const title = ((_a = question.split("\n")[0]) != null ? _a : "").slice(0, 80).replace(/\?$/, "") || "Research note";
    const allNotes = await listNotes(app, { limit: 300 });
    if (settings.toggles.estimate_token_usage && onTokenEstimate) {
      const { estimates } = await relatedLookupEstimates(app, settings, snapshots, title, question, allNotes);
      if (estimates.length) onTokenEstimate(estimates);
    }
    const { notes: related, warnings: relatedWarnings, links: relatedLinks } = await relatedForNewNote(
      app,
      settings,
      snapshots,
      title,
      question,
      allNotes
    );
    const snapshotContext = snapshotsAsContext(snapshots);
    if (settings.toggles.estimate_token_usage && onTokenEstimate) {
      onTokenEstimate(
        estimateGenerateNoteTokens({
          settings,
          source_label: "User question",
          source_text: question,
          user_prompt: DIRECT_QUESTION_USER_PROMPT,
          related_notes: related,
          related_links: relatedLinks,
          source_generation: false,
          question,
          snapshotContext
        })
      );
    }
    const { body, warnings } = await generateNote({
      settings,
      source_label: "User question",
      source_text: question,
      user_prompt: DIRECT_QUESTION_USER_PROMPT,
      related_notes: related,
      related_links: relatedLinks,
      source_generation: false,
      question,
      snapshotContext
    });
    const written = await writeNote(app, settings.output_folder, title, body);
    return {
      ok: true,
      path: written.path,
      title: written.title,
      warnings: [...relatedWarnings, ...warnings],
      content_type: "question"
    };
  } catch (e) {
    return { ok: false, error: e instanceof Error ? e.message : String(e) };
  }
}
function estimateSnapshotRefresh(settings, notes) {
  const estimates = notes.map((n) => estimateSnapshotTokens(n.title, n.relative_path, n.body));
  return {
    notes: notes.length,
    estimate: combineEstimates("Snapshot creation", estimates)
  };
}
async function refreshMemory(app, settings) {
  try {
    const notes = await listNotes(app, { limit: null, bodyLimit: null, excludeAttachmentNotes: true });
    const items = [];
    for (const note of notes) {
      const summary = await summarizeForSnapshot(settings, note.title, note.relative_path, note.body);
      items.push({ relative_path: note.relative_path, title: note.title, summary });
    }
    const snapshots = replaceSnapshots(items);
    return { ok: true, updated: snapshots.length, snapshots };
  } catch (e) {
    return { ok: false, error: e instanceof Error ? e.message : String(e) };
  }
}
function shouldShowSnapshotRefresh(settings) {
  return settings.toggles.compare_existing_notes && settings.related_notes_mode === "snapshot";
}

// src/views/InsiderView.ts
var VIEW_TYPE_INSIDER = "insider-sidebar";
var InsiderView = class extends import_obsidian8.ItemView {
  constructor(leaf, plugin) {
    super(leaf);
    this.busy = false;
    this.plugin = plugin;
  }
  getViewType() {
    return VIEW_TYPE_INSIDER;
  }
  getDisplayText() {
    return "Insider";
  }
  getIcon() {
    return "sparkles";
  }
  async onOpen() {
    this.render();
  }
  async onClose() {
  }
  render() {
    const { contentEl } = this;
    contentEl.empty();
    contentEl.addClass("insider-view");
    contentEl.createEl("h4", { text: "Insider" });
    this.statusEl = contentEl.createDiv({ cls: "insider-status" });
    this.renderStatus();
    const opt1 = contentEl.createDiv({ cls: "insider-section" });
    opt1.createEl("h5", { text: "1. Generate from URL or PDF" });
    const sourceInput = opt1.createEl("input", {
      type: "text",
      placeholder: "Paste URL or vault PDF path",
      cls: "insider-input"
    });
    const instructionsInput = opt1.createEl("textarea", {
      placeholder: "Optional instructions",
      cls: "insider-textarea"
    });
    instructionsInput.rows = 2;
    const genBtn = opt1.createEl("button", { text: "Generate note", cls: "mod-cta" });
    genBtn.onclick = () => this.run(async () => {
      const source = sourceInput.value.trim();
      if (!source) {
        new import_obsidian8.Notice("Enter a URL or PDF path.");
        return;
      }
      await this.runSource(source, instructionsInput.value.trim());
    });
    const opt2 = contentEl.createDiv({ cls: "insider-section" });
    opt2.createEl("h5", { text: "2. Ask a question" });
    const questionInput = opt2.createEl("textarea", {
      placeholder: "Ask a question\u2026",
      cls: "insider-textarea"
    });
    questionInput.rows = 4;
    const askBtn = opt2.createEl("button", { text: "Ask and write report", cls: "mod-cta" });
    askBtn.onclick = () => this.run(async () => {
      const question = questionInput.value.trim();
      if (!question) {
        new import_obsidian8.Notice("Enter a question.");
        return;
      }
      await this.runQuestion(question);
    });
    const togglesSection = contentEl.createDiv({ cls: "insider-section insider-toggles" });
    togglesSection.createEl("h5", { text: "Options" });
    this.renderToggles(togglesSection);
    this.snapshotSectionEl = contentEl.createDiv({ cls: "insider-section insider-snapshot-section" });
    this.renderSnapshotSection();
    contentEl.createEl("p", {
      cls: "insider-hint",
      text: "Settings persist automatically. Configure API key under Settings \u2192 Insider."
    });
  }
  renderStatus() {
    const s = this.plugin.settings;
    const snapCount = listSnapshots(this.plugin.snapshots).length;
    const keyOk = Boolean(s.deepseek_api_key.trim());
    this.statusEl.empty();
    this.statusEl.createEl("span", {
      text: keyOk ? "API key: set" : "API key: missing",
      cls: keyOk ? "insider-ok" : "insider-warn"
    });
    this.statusEl.createEl("span", { text: ` \xB7 Output: ${s.output_folder}` });
    this.statusEl.createEl("span", { text: ` \xB7 Snapshots: ${snapCount}` });
  }
  renderToggles(container) {
    const s = this.plugin.settings;
    const addToggle = (name, desc, get, set) => {
      new import_obsidian8.Setting(container).setName(name).setDesc(desc).addToggle(
        (t) => t.setValue(get()).onChange(async (v) => {
          set(v);
          await this.plugin.saveSettings();
          this.renderSnapshotSection();
          this.renderStatus();
        })
      );
    };
    addToggle(
      "Compare with existing notes",
      "Find related vault notes and add compare/contrast context.",
      () => s.toggles.compare_existing_notes,
      (v) => {
        s.toggles.compare_existing_notes = v;
      }
    );
    new import_obsidian8.Setting(container).setName("Related-note algorithm").addDropdown(
      (d) => d.addOption("snapshot", "Semantic snapshot").addOption("keyword", "Keyword overlap").setValue(s.related_notes_mode).onChange(async (v) => {
        s.related_notes_mode = v === "keyword" ? "keyword" : "snapshot";
        await this.plugin.saveSettings();
        this.renderSnapshotSection();
      })
    );
    new import_obsidian8.Setting(container).setName("Output mode").addDropdown(
      (d) => d.addOption("report", "Report").addOption("summary", "Summary").setValue(s.mode).onChange(async (v) => {
        s.mode = v === "summary" ? "summary" : "report";
        await this.plugin.saveSettings();
      })
    );
    addToggle("Suggested follow-up note ideas", "", () => s.toggles.recommend_note_ideas, (v) => {
      s.toggles.recommend_note_ideas = v;
    });
    addToggle("Show token estimates", "", () => s.toggles.estimate_token_usage, (v) => {
      s.toggles.estimate_token_usage = v;
    });
    addToggle("YouTube timestamps", "", () => s.toggles.include_timestamps, (v) => {
      s.toggles.include_timestamps = v;
    });
    addToggle("Strip audio cues", "Remove [Music], [Applause], etc.", () => s.toggles.strip_audio_cues, (v) => {
      s.toggles.strip_audio_cues = v;
    });
    new import_obsidian8.Setting(container).setName("Max related notes").addSlider(
      (sl) => sl.setLimits(0, 10, 1).setValue(s.max_related_notes).setDynamicTooltip().onChange(async (v) => {
        s.max_related_notes = v;
        await this.plugin.saveSettings();
      })
    );
    new import_obsidian8.Setting(container).setName("Max Reddit comments").addSlider(
      (sl) => sl.setLimits(0, 50, 5).setValue(s.reddit_max_comments).setDynamicTooltip().onChange(async (v) => {
        s.reddit_max_comments = v;
        await this.plugin.saveSettings();
      })
    );
  }
  renderSnapshotSection() {
    this.snapshotSectionEl.empty();
    if (!shouldShowSnapshotRefresh(this.plugin.settings)) return;
    this.snapshotSectionEl.createEl("h5", { text: "Semantic snapshots" });
    this.snapshotSectionEl.createEl("p", {
      cls: "insider-hint",
      text: "Required for snapshot-based related-note linking. Creates one DeepSeek call per vault note."
    });
    const refreshBtn = this.snapshotSectionEl.createEl("button", { text: "Refresh semantic snapshots" });
    refreshBtn.onclick = () => this.run(() => this.runSnapshotRefresh());
  }
  async run(fn) {
    if (this.busy) return;
    this.busy = true;
    try {
      await fn();
    } finally {
      this.busy = false;
    }
  }
  showTokenEstimates(estimates) {
    if (!estimates.length) return;
    const total = combineEstimates("Estimated DeepSeek usage", estimates);
    const lines = estimates.map(formatTokenEstimate);
    lines.push(`Total: ~${totalTokens(total).toLocaleString()} combined`);
    new import_obsidian8.Notice(lines.join("\n"), 8e3);
  }
  async runSource(source, userPrompt) {
    if (!this.plugin.settings.deepseek_api_key.trim()) {
      new import_obsidian8.Notice("Set your DeepSeek API key in Settings \u2192 Insider.");
      return;
    }
    new import_obsidian8.Notice("Fetching and generating\u2026");
    const estimates = [];
    const result = await processSource(
      this.app,
      this.plugin.settings,
      this.plugin.snapshots,
      source,
      userPrompt,
      (e) => {
        if (this.plugin.settings.toggles.estimate_token_usage) estimates.push(...e);
      }
    );
    if (result.updatedSnapshots) {
      this.plugin.snapshots = result.updatedSnapshots;
      await this.plugin.saveSettings();
    }
    if (this.plugin.settings.toggles.estimate_token_usage && estimates.length) {
      this.showTokenEstimates(estimates);
    }
    this.finishResult(result);
    this.renderStatus();
  }
  async runQuestion(question) {
    if (!this.plugin.settings.deepseek_api_key.trim()) {
      new import_obsidian8.Notice("Set your DeepSeek API key in Settings \u2192 Insider.");
      return;
    }
    new import_obsidian8.Notice("Generating report\u2026");
    const estimates = [];
    const result = await processQuestion(
      this.app,
      this.plugin.settings,
      this.plugin.snapshots,
      question,
      (e) => {
        if (this.plugin.settings.toggles.estimate_token_usage) estimates.push(...e);
      }
    );
    if (this.plugin.settings.toggles.estimate_token_usage && estimates.length) {
      this.showTokenEstimates(estimates);
    }
    this.finishResult(result);
  }
  async runSnapshotRefresh() {
    var _a;
    if (!this.plugin.settings.deepseek_api_key.trim()) {
      new import_obsidian8.Notice("Set your DeepSeek API key in Settings \u2192 Insider.");
      return;
    }
    const notes = await listNotes(this.app, { limit: null, bodyLimit: null, excludeAttachmentNotes: true });
    if (this.plugin.settings.toggles.estimate_token_usage) {
      const { notes: count, estimate } = estimateSnapshotRefresh(this.plugin.settings, notes);
      new import_obsidian8.Notice(`Notes to scan: ${count}
${formatTokenEstimate(estimate)}`, 8e3);
    }
    const confirmed = await askConfirm(
      this.app,
      `Create semantic snapshots for ${notes.length} notes? This calls DeepSeek once per note.`
    );
    if (!confirmed) return;
    new import_obsidian8.Notice("Refreshing snapshots\u2026 this may take a while.");
    const result = await refreshMemory(this.app, this.plugin.settings);
    if (result.ok && result.snapshots) {
      this.plugin.snapshots = result.snapshots;
      await this.plugin.saveSettings();
      new import_obsidian8.Notice(`Created/refreshed ${result.updated} semantic snapshots.`);
      this.renderStatus();
    } else {
      new import_obsidian8.Notice(`Error: ${(_a = result.error) != null ? _a : "Unknown error"}`);
    }
  }
  finishResult(result) {
    var _a, _b;
    if (!result.ok) {
      new import_obsidian8.Notice(`Error: ${(_a = result.error) != null ? _a : "Unknown error"}`);
      return;
    }
    let msg = `Wrote: ${result.path}`;
    if ((_b = result.warnings) == null ? void 0 : _b.length) {
      msg += `
Warnings: ${result.warnings.slice(0, 3).join("; ")}`;
    }
    new import_obsidian8.Notice(msg, 6e3);
  }
};
function askConfirm(app, message) {
  return new Promise((resolve) => {
    new ConfirmModal(app, message, resolve).open();
  });
}
var ConfirmModal = class extends import_obsidian8.Modal {
  constructor(app, message, resolve) {
    super(app);
    this.message = message;
    this.resolve = resolve;
  }
  onOpen() {
    const { contentEl } = this;
    contentEl.createEl("p", { text: this.message });
    new import_obsidian8.Setting(contentEl).addButton((btn) => btn.setButtonText("Cancel").onClick(() => {
      this.resolve(false);
      this.close();
    })).addButton((btn) => btn.setButtonText("Continue").setCta().onClick(() => {
      this.resolve(true);
      this.close();
    }));
  }
  onClose() {
    this.contentEl.empty();
  }
};

// src/main.ts
var INSIDER_ICON = `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><path d="M12 3l1.5 4.5L18 9l-4.5 1.5L12 15l-1.5-4.5L6 9l4.5-1.5L12 3z"/><path d="M5 19l1 3 1-3 3-1-3-1-1-3-1 3-3 1 3 1z"/><path d="M19 13l.5 1.5 1.5.5-1.5.5-.5 1.5-.5-1.5-1.5-.5 1.5-.5.5-1.5z"/></svg>`;
var InsiderPlugin = class extends import_obsidian9.Plugin {
  constructor() {
    super(...arguments);
    this.settings = mergeSettings(void 0);
    this.snapshots = [];
  }
  async onload() {
    (0, import_obsidian9.addIcon)("insider-sparkles", INSIDER_ICON);
    await this.loadSettings();
    this.registerView(VIEW_TYPE_INSIDER, (leaf) => new InsiderView(leaf, this));
    this.addRibbonIcon("insider-sparkles", "Open Insider", () => {
      void this.activateView();
    });
    this.addCommand({
      id: "open-sidebar",
      name: "Open sidebar",
      callback: () => {
        void this.activateView();
      }
    });
    this.addSettingTab(new InsiderSettingTab(this.app, this));
  }
  async loadSettings() {
    var _a;
    const data = await this.loadData();
    this.settings = mergeSettings(data == null ? void 0 : data.settings);
    this.snapshots = (_a = data == null ? void 0 : data.snapshots) != null ? _a : [];
  }
  async saveSettings() {
    const data = {
      settings: this.settings,
      snapshots: this.snapshots
    };
    await this.saveData(data);
  }
  async activateView() {
    var _a;
    const { workspace } = this.app;
    let leaf = (_a = workspace.getLeavesOfType(VIEW_TYPE_INSIDER)[0]) != null ? _a : null;
    if (!leaf) {
      const rightLeaf = workspace.getRightLeaf(false);
      if (!rightLeaf) return;
      await rightLeaf.setViewState({ type: VIEW_TYPE_INSIDER, active: true });
      leaf = rightLeaf;
    }
    await workspace.revealLeaf(leaf);
  }
};
